package main

func handleError(err error) {
	panic(err)
}
